openapi: 3.0.0
info:
  title: Order Read Cache API
  version: @VERSION@
servers:
- url: https://localhost/v1
tags:
- name: orderReadCache
paths:
  /orders:
    get:
      tags:
      - orderReadCache
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
      operationId: GetOrders
  /orders/{orderId}:
    get:
      tags:
      - orderReadCache
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      operationId: GetOrderByOrderId
    parameters:
    - name: orderId
      in: path
      required: true
      schema:
        type: string
  /products/{productId}/orders:
    get:
      tags:
      - orderReadCache
      responses:
        200:
          description: 'order per product'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
      operationId: GetOrdersByProductsId
    parameters:
    - name: orderId
      in: path
      required: true
      schema:
        type: string
components:
  schemas:
    order:
      type: object
      properties:
        id:
          type: string
        version:
          type: integer
          format: int64
        price:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/orderItem'
        createdOn:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
      required:
      - id
      - version
      - price
      - items
      - createdOn
      - lastModified
    orderItem:
      type: object
      properties:
        quantity:
          type: integer
          format: int64
        productId:
          type: string
        price:
          type: number
      required:
      - quantity
      - productId
      - price
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
