openapi: 3.0.0
info:
  title: Product API
  version: @VERSION@
servers:
  - url: https://localhost/v1
paths:
  /products:
    get:
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
      operationId: GetProducts
  /products/{productId}:
    get:
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
      operationId: GetProductByProductId
    parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: string
  /orders:
    get:
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
      operationId: GetOrders
    post:
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      operationId: PostOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orderInput'
        required: true
  /orders/{orderId}:
    get:
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      operationId: GetOrderByOrderId
    put:
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
      operationId: PutOrderByOrderId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orderInput'
        required: true
    delete:
      responses:
        200:
          description: ''
      operationId: DeleteOrderByOrderId
    parameters:
    - name: orderId
      in: path
      required: true
      schema:
        type: integer
        format: int64
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        releaseDate:
          type: string
          format: date
        createdOn:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
      required:
      - id
      - name
      - price
      - releaseDate
      - createdOn
      - lastModified
    order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        version:
          type: integer
          format: int64
        price:
          type: number
        items:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: integer
                format: int32
              productId:
                type: string
              price:
                type: number
            required:
              - quantity
              - productId
              - price
        createdOn:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
      required:
      - id
      - version
      - price
      - items
      - createdOn
      - lastModified
    orderInput:
      type: object
      properties:
        version:
          type: integer
          format: int64
        items:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: integer
                format: int32
              productId:
                type: string
            required:
              - quantity
              - productId
      required:
      - items
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
